kind: pipeline
name: migrations

global-variables:
  db_env: &db_env
    DB_DSN: 'root:test@tcp(migration-db:3306)/stats'

steps:
- name: migrate
  image: gobridget/mig:latest
  pull: always
  environment:
    <<: *db_env
  commands:
  - sleep 10
  - mig create --migrate-path example/schema --db-dsn "root:test@tcp(migration-db:3306)/mysql" --apply
  - mig migrate --migrate-path example/schema --project=stats --apply
  - mig docs --schema=stats
  - mig gen --schema=stats --lang=go --output=example/gen_go
  - mig gen --schema=stats --lang=php81 --output=example/gen_php81
  - mig lint --schema=stats
  - mig version

- name: migrate-env
  image: gobridget/mig:latest
  pull: never
  environment:
    DB_DSN: root:test@tcp(migration-db:3306)/mysql
  commands:
  - mig create --migrate-path example/schema --apply
  - mig migrate --migrate-path example/schema --project=stats --apply
  - mig version

services:
- name: migration-db
  pull: always
  image: percona:8.0
  ports:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: test
