kind: pipeline
name: migrations

steps:
- name: migrate
  image: bridget/mig:latest
  pull: never
  commands:
  - mig create --migrate-path test/schema --db-dsn "root:test@tcp(migration-db:3306)/mysql" --apply
  - mig migrate --migrate-path test/schema --project=stats --db-dsn "root:test@tcp(migration-db:3306)/stats" --apply
  - mig docs --schema=stats --db-dsn "root:test@tcp(migration-db:3306)/stats"
  - mig lint --schema=stats --db-dsn "root:test@tcp(migration-db:3306)/stats"
  - mig version

- name: migrate-env
  image: bridget/mig:latest
  pull: never
  environment:
    DB_DSN: root:test@tcp(migration-db:3306)/mysql
  commands:
  - mig create --migrate-path test/schema --apply
  - mig migrate --migrate-path test/schema --project=stats --apply
  - mig version

services:
- name: migration-db
  pull: always
  image: percona:8.0
  ports:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: test
