---
version: "3"

includes:
  docker: Taskfile.docker.yml

env:
  CGO_ENABLED: 0

vars:
  version:
    sh: git describe --always --tags --abbrev=8
  time:
    sh: date +%Y-%m-%dT%T%z
  package:
    sh: go mod edit -json | jq .Module.Path -r
  ldflags: -ldflags "-X 'main.BuildVersion={{.version}}' -X 'main.BuildTime={{.time}}'"

tasks:
  default:
    cmds:
      - go mod tidy
      - goimports -w -local {{.package}} .
      - go install {{.ldflags}} ./cmd/...
      - task: test

  build:
    cmds:
      - go build -o build/ {{.ldflags}} ./cmd/...
      - docker build -t go-bridget/mig -f docker/Dockerfile .

  test:
    desc: "Run tests for all databases"
    deps: [docker:up]
    cmds:
      - defer: { task: docker:down }
      - task: test:sqlite
      - task: test:mysql
      - task: test:postgresql

  test:sqlite:
    desc: "Test with SQLite"
    cmds:
      - mig migrate events --path testdata/events/sqlite --db-dsn "sqlite://:memory:" --apply --verbose
      - mig migrate events --path testdata/events/sqlite --db-dsn "sqlite://test.db" --apply --verbose
      - mig lint --db-dsn "file:test.db" --skip-comments
      - mkdir -p testdata/docs-sqlite
      - mig docs --output=testdata/docs-sqlite --output-file=schema.yaml --yaml --db-dsn "sqlite://test.db"
      - mig gen --lang=go --db-dsn "sqlite://test.db" --output testdata/sqlite/model

  test:mysql:
    desc: "Test with MySQL"
    env:
      DB_DSN: 'mysql://root:test@tcp(localhost:13306)/events'
    cmds:
      - mig create events --db-dsn "mysql://root:test@tcp(localhost:13306)/mysql" --apply
      - mig migrate events --path testdata/events/mysql --apply
      - mig lint
      - go test -v -tags integration ./...
      - mkdir -p testdata/docs-mysql
      - mig docs --output=testdata/docs-mysql --output-file=schema.yaml --yaml
      - mig gen --lang=go --output=testdata/gen_go
      - mig version

  test:postgresql:
    desc: "Test with PostgreSQL"
    env:
      DB_DSN: 'postgres://postgres:mig@localhost:15432/events?sslmode=disable'
      PGPASSWORD: mig
    cmds:
      - psql -h localhost -p 15432 -U postgres -c "CREATE DATABASE IF NOT EXISTS events" 2>/dev/null || psql -h localhost -p 15432 -U postgres -c "CREATE DATABASE events" 2>/dev/null || true
      - mig migrate events --path testdata/events/postgres --apply
      - mig lint
      - mkdir -p testdata/docs-postgresql
      - mig docs --output=testdata/docs-postgresql --output-file=schema.yaml --yaml

  test:inspect:
    desc: "Compare schemas (filtered to name, normalized_type, enum_values)"
    cmds:
      - mkdir -p testdata/inspect
      - mig-filter-schema testdata/docs-sqlite/schema.yaml > testdata/inspect/sqlite.yaml
      - mig-filter-schema testdata/docs-mysql/schema.yaml > testdata/inspect/mysql.yaml
      - mig-filter-schema testdata/docs-postgresql/schema.yaml > testdata/inspect/postgresql.yaml
      - dyff between -i testdata/inspect/sqlite.yaml testdata/inspect/mysql.yaml || true
      - dyff between -i testdata/inspect/sqlite.yaml testdata/inspect/postgresql.yaml || true
      - dyff between -i testdata/inspect/mysql.yaml testdata/inspect/postgresql.yaml || true
