package model

// Code generated by go-bridget/mig. DO NOT EDIT.

// Migrations generated for db table `migrations`.
type Migrations struct {
	// Project
	Project string `db:"project" json:"-"`

	// Filename
	Filename string `db:"filename" json:"-"`

	// Statement Index
	StatementIndex int64 `db:"statement_index" json:"-"`

	// Status
	Status string `db:"status" json:"-"`
}

// GetProject will return the value of Project.
func (m *Migrations) GetProject() string { return m.Project }

// GetFilename will return the value of Filename.
func (m *Migrations) GetFilename() string { return m.Filename }

// GetStatementIndex will return the value of StatementIndex.
func (m *Migrations) GetStatementIndex() int64 { return m.StatementIndex }

// GetStatus will return the value of Status.
func (m *Migrations) GetStatus() string { return m.Status }

// MigrationsTable is the name of the table in the DB.
const MigrationsTable = "`migrations`"

// MigrationsFields is a list of all columns in the DB table.
var MigrationsFields = []string{"project", "filename", "statement_index", "status"}

// MigrationsPrimaryFields are the primary key fields in the DB table.
var MigrationsPrimaryFields = []string{"project"}

// Stats generated for db table `stats`.
type Stats struct {
	// ID
	ID int64 `db:"id" json:"-"`

	// Payload
	Payload string `db:"payload" json:"-"`
}

// GetID will return the value of ID.
func (s *Stats) GetID() int64 { return s.ID }

// GetPayload will return the value of Payload.
func (s *Stats) GetPayload() string { return s.Payload }

// StatsTable is the name of the table in the DB.
const StatsTable = "`stats`"

// StatsFields is a list of all columns in the DB table.
var StatsFields = []string{"id", "payload"}

// StatsPrimaryFields are the primary key fields in the DB table.
var StatsPrimaryFields = []string{"id"}
