package gen_go

// Code generated by go-bridget/mig. DO NOT EDIT.

import (
	"fmt"
	"strings"
)

type QueryOption interface {
	WithTable(name string) QueryOption
	WithColumns(cols []string) QueryOption
	WithWhere(clause string) QueryOption
	WithOrderBy(clause string) QueryOption
	WithLimit(start, offset int) QueryOption
	WithStatement(stmt string) QueryOption
}

type QueryConfig struct {
	Table       string
	Columns     []string
	Where       string
	OrderBy     string
	LimitStart  int
	LimitOffset int
	Statement   string
}

func (q *QueryConfig) WithTable(name string) QueryOption {
	q.Table = name
	return q
}

func (q *QueryConfig) WithColumns(cols []string) QueryOption {
	q.Columns = cols
	return q
}

func (q *QueryConfig) WithWhere(clause string) QueryOption {
	q.Where = clause
	return q
}

func (q *QueryConfig) WithOrderBy(clause string) QueryOption {
	q.OrderBy = clause
	return q
}

func (q *QueryConfig) WithLimit(start, offset int) QueryOption {
	q.LimitStart = start
	q.LimitOffset = offset
	return q
}

func (q *QueryConfig) WithStatement(stmt string) QueryOption {
	q.Statement = stmt
	return q
}

func WithTable(name string) QueryOption {
	return &QueryConfig{Table: name}
}

func WithColumns(cols []string) QueryOption {
	return &QueryConfig{Columns: cols}
}

func WithWhere(clause string) QueryOption {
	return &QueryConfig{Where: clause}
}

func WithOrderBy(clause string) QueryOption {
	return &QueryConfig{OrderBy: clause}
}

func WithLimit(start, offset int) QueryOption {
	return &QueryConfig{LimitStart: start, LimitOffset: offset}
}

func WithStatement(stmt string) QueryOption {
	return &QueryConfig{Statement: stmt}
}

func (q *QueryConfig) Apply(opts ...QueryOption) *QueryConfig {
	cfg := *q
	for _, opt := range opts {
		o := opt.(*QueryConfig)
		if o.Table != "" {
			cfg.Table = o.Table
		}
		if len(o.Columns) > 0 {
			cfg.Columns = o.Columns
		}
		if o.Where != "" {
			cfg.Where = o.Where
		}
		if o.OrderBy != "" {
			cfg.OrderBy = o.OrderBy
		}
		if o.LimitOffset > 0 {
			cfg.LimitStart = o.LimitStart
			cfg.LimitOffset = o.LimitOffset
		}
		if o.Statement != "" {
			cfg.Statement = o.Statement
		}
	}
	return &cfg
}

// Asset generated for db table `asset`.
//
// Stores asset information for each commit.
type Asset struct {
}

// AssetTable is the name of the table in the DB.
const AssetTable = "`asset`"

// AssetFields is a list of all columns in the DB table.
var AssetFields = []string{}

// AssetPrimaryFields are the primary key fields in the DB table.
var AssetPrimaryFields = []string{}

// Branch generated for db table `branch`.
//
// Stores information about branches in repositories.
type Branch struct {
}

// BranchTable is the name of the table in the DB.
const BranchTable = "`branch`"

// BranchFields is a list of all columns in the DB table.
var BranchFields = []string{}

// BranchPrimaryFields are the primary key fields in the DB table.
var BranchPrimaryFields = []string{}

// Commit generated for db table `commit`.
//
// Stores information about commits in branches.
type Commit struct {
}

// CommitTable is the name of the table in the DB.
const CommitTable = "`commit`"

// CommitFields is a list of all columns in the DB table.
var CommitFields = []string{}

// CommitPrimaryFields are the primary key fields in the DB table.
var CommitPrimaryFields = []string{}

// Migrations generated for db table `migrations`.
//
// Migration log of applied migrations.
type Migrations struct {
}

// MigrationsTable is the name of the table in the DB.
const MigrationsTable = "`migrations`"

// MigrationsFields is a list of all columns in the DB table.
var MigrationsFields = []string{}

// MigrationsPrimaryFields are the primary key fields in the DB table.
var MigrationsPrimaryFields = []string{}

// Repository generated for db table `repository`.
//
// Stores basic information about repositories.
type Repository struct {
}

// RepositoryTable is the name of the table in the DB.
const RepositoryTable = "`repository`"

// RepositoryFields is a list of all columns in the DB table.
var RepositoryFields = []string{}

// RepositoryPrimaryFields are the primary key fields in the DB table.
var RepositoryPrimaryFields = []string{}

func (a *Asset) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: AssetTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := AssetFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

func (a *Asset) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: AssetTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

func (a *Asset) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: AssetTable}).Apply(opts...)
	cols := AssetFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

func (a *Asset) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: AssetTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

func (b *Branch) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: BranchTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := BranchFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

func (b *Branch) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: BranchTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

func (b *Branch) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: BranchTable}).Apply(opts...)
	cols := BranchFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

func (b *Branch) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: BranchTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

func (c *Commit) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: CommitTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := CommitFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

func (c *Commit) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: CommitTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

func (c *Commit) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: CommitTable}).Apply(opts...)
	cols := CommitFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

func (c *Commit) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: CommitTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

func (m *Migrations) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := MigrationsFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

func (m *Migrations) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

func (m *Migrations) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable}).Apply(opts...)
	cols := MigrationsFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

func (m *Migrations) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

func (r *Repository) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: RepositoryTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := RepositoryFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

func (r *Repository) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: RepositoryTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

func (r *Repository) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: RepositoryTable}).Apply(opts...)
	cols := RepositoryFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

func (r *Repository) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: RepositoryTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}
